name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  scheduled:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22
      - name: Install dependencies
        run: npm ci
      - name: Fetch latest data
        env:
          MOONBOARD_USERNAME: ${{ secrets.MOONBOARDAPP_USERNAME }}
          MOONBOARD_PASSWORD: ${{ secrets.MOONBOARDAPP_PASSWORD }}
          KILTERBOARDAPP_USERNAME: ${{ secrets.KILTERBOARDAPP_USERNAME }}
          KILTERBOARDAPP_PASSWORD: ${{ secrets.KILTERBOARDAPP_PASSWORD }}
          TENSIONBOARDAPP2_USERNAME: ${{ secrets.TENSIONBOARDAPP2_USERNAME }}
          TENSIONBOARDAPP2_PASSWORD: ${{ secrets.TENSIONBOARDAPP2_PASSWORD }}
          GRASSHOPPERBOARDAPP_USERNAME: ${{ secrets.GRASSHOPPERBOARDAPP_USERNAME }}
          GRASSHOPPERBOARDAPP_PASSWORD: ${{ secrets.GRASSHOPPERBOARDAPP_PASSWORD }}
          DECOYBOARDAPP_USERNAME: ${{ secrets.DECOYBOARDAPP_USERNAME }}
          DECOYBOARDAPP_PASSWORD: ${{ secrets.DECOYBOARDAPP_PASSWORD }}
          SOILLBOARDAPP_USERNAME: ${{ secrets.SOILLBOARDAPP_USERNAME }}
          SOILLBOARDAPP_PASSWORD: ${{ secrets.SOILLBOARDAPP_PASSWORD }}
          TOUCHSTONEBOARDAPP_USERNAME: ${{ secrets.TOUCHSTONEBOARDAPP_USERNAME }}
          TOUCHSTONEBOARDAPP_PASSWORD: ${{ secrets.TOUCHSTONEBOARDAPP_PASSWORD }}
          AURORABOARDAPP_USERNAME: ${{ secrets.AURORABOARDAPP_USERNAME }}
          AURORABOARDAPP_PASSWORD: ${{ secrets.AURORABOARDAPP_PASSWORD }}
        run: |-
          npm run scrape;
          npm run convert;
          npm run combine;
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
